<style type="text/css">
    table{
        border-collapse: collapse;
    }
    table,tbody, tr, td {border: 0;}
</style>
<table width="1080px" background="http://rosesonly.com.sg/skin/frontend/default/f002/images/custom_bg.png" style="border-spacing:0;padding: 0;border: 0;font-family: Calibri;color:#000;margin:auto;">
    <tr style="border: 0;">
        <td width="189px"></td>
        <td> 
            <div style="padding-top:30px;color:#333; font-weight:bold;font-size:14px;margin:auto; text-align:center">
                Does this page look broken? View it in your <a href="http://rosesonly.com.sg/special/picean/edm" style="color: #231f20;">web browser ></a>
            </div>

            <div class="header-break" style="width: 695px;height:10px;background-color:#76A192;"></div>
            <table width="695px" bgcolor="#fff" style="border-spacing:0px;background-color:#fff;">
                <tr>
                    <td>
                        <div class="head">
                            <table width="100%;" style= "border: 0;border-spacing: 0;">
                                <tr>
                                    <td width="155px">
                                        <div class="head-logo" style="width:155px;float:left;padding-top: 15px;padding-left: 10px;">
                                            <a href="http://rosesonly.com.sg/">
                                                <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/edm_thankyou_logo.png" />
                                            </a>
                                        </div>
                                    </td>
                                    <td text-align="right">
                                        <div class="head-bar">
                                            <div class="social" style="padding: 40px 20px 0;float:right;">
                                                <!-- AddThis Button BEGIN -->
                                                <span style="float:left; padding: 5px 10px;">Share</span>
                                                <a href="http://api.addthis.com/oexchange/0.8/forward/facebook/offer?pco=tbx32nj-1.0&url=http://rosesonly.com.sg&pubid=ra-50b6d2b601c4ca21" target="_blank" ><img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/23x23/facebook.png" border="0" alt="Facebook" /></a>
                                                <a href="http://api.addthis.com/oexchange/0.8/forward/twitter/offer?pco=tbx32nj-1.0&url=http%://rosesonly.com.sg&pubid=ra-50b6d2b601c4ca21" target="_blank" ><img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/23x23/twitter.png" border="0" alt="Twitter" /></a>
                                                <!--a href="http://api.addthis.com/oexchange/0.8/forward/pinterest/offer?pco=tbx32nj-1.0&url=http%3A%2F%2Frosesonly.com.sg&pubid=ra-50b6d2b601c4ca21" target="_blank" ><img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/23x23/pinterest.png" border="0" alt="Twitter" /></a-->
                                                <a href="http://api.addthis.com/oexchange/0.8/forward/email/offer?pco=tbx32nj-1.0&url=http://rosesonly.com.sg&pubid=ra-50b6d2b601c4ca21" target="_blank" ><img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/23x23/email.png" border="0" alt="Twitter" /></a>
                                                <!-- AddThis Button END -->
                                            </div>
                                            <div style="clear:both;"></div>
                                            <div class="menu" style="float:right;padding: 15px 20px 0;">
                                                <a href="http://rosesonly.com.sg" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;">Home</a>
                                                <a href="http://rosesonly.com.sg/birthday.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;">Birthday</a>
                                                <a href="http://rosesonly.com.sg/occation.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;">Occasion</a>
                                                <a href="http://rosesonly.com.sg/recipent.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;">Recipient</a>
                                                <a href="http://rosesonly.com.sg/style.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;">Style</a>
                                                <a href="http://rosesonly.com.sg/whats-new/intl-women-s-day.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;">What's new </a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>                                    
                            </table>                               

                            <div style="clear:both;"></div>
                    </td>
                </tr>
            </table>
            </div>
        </td>
        <td width="190px" style="border: 0;"></td>
    </tr>
    <tr>        
        <td colspan="3">
            <div name="ribbon" style="width: 100%; height: 100%; display: block;clear: both;position: relative;margin-top:-2px;"> 
                <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/picean/ribbon.png" />
            </div>
        </td>        
    </tr>
    <tr>
        <td width="189px" style="border: 0;"></td>
        <td style="background-color: #f2ecdf;">            
            <div style="margin-top: -6px; background-color: #f2ecdf;">
                <a href="http://rosesonly.com.sg/whats-new/surprise-the-piscean.html">
                    <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/picean/p1.png" />
                </a>
            </div>
            <div style="background-color: #fff;width:652px; margin:auto; margin-top:15px;border-radius:12px 12px 0 0;">
                <div style="float:left;">
                    <a href="http://rosesonly.com.sg/whats-new/surprise-the-piscean/hail-the-poet-12-labelle-roses.html">
                        <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/picean/p2.png" />
                    </a>
                </div>
                <div style="float:left;padding:30px 10px;">
                    <a href="http://rosesonly.com.sg/whats-new/surprise-the-piscean/hail-the-poet-12-labelle-roses.html">
                        <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/picean/p3.png" />
                    </a>
                </div>
                <div style="clear:both;"></div>                
            </div>           
            <div style="background-color: #fff;width:652px; margin:auto; ">
                <div style="float:left;margin: 10px 0 0 -10px;">
                    <a href="http://rosesonly.com.sg/whats-new/surprise-the-piscean/for-the-dreamer-12-labelle-roses-with-peter.html">
                        <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/picean/p4.png" />
                    </a>
                </div>
                <div style="float:right; margin-top:-120px;">
                    <a href="http://rosesonly.com.sg/whats-new/surprise-the-piscean/for-the-dreamer-12-labelle-roses-with-peter.html">
                        <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/picean/p5.png" />
                    </a>
                </div>
                <div style="clear:both;"></div>   
            </div>
        </td>
        <td width="210px" style="border: 0;"></td>
    </tr>
    <tr>
        <td colspan="3">
            <div style="margin-top:-2px;">
                <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/picean/p6.png" />
            </div>
        </td>
    </tr>
    <tr>
        <td width="189px" style="border: 0;"></td>
        <td  style="background-color: #f2ecdf;">
            <div style="margin-top:-6px;background-color: #f2ecdf;">
            <div style="background-color: #fff;width:652px; margin:auto; border-radius: 0 0 12px 12px; padding-bottom:5px;">
                <div style="float:left;">
                    <a href="http://rosesonly.com.sg/whats-new/surprise-the-piscean/the-hopeless-romantic-12-labelle-roses-with-moet-chandon-375ml.html">
                        <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/picean/p7.png" />
                    </a>
                </div>
                <div style="float:right;margin:80px -15px 0 0;">
                    <a href="http://rosesonly.com.sg/whats-new/surprise-the-piscean/the-hopeless-romantic-12-labelle-roses-with-moet-chandon-375ml.html">
                        <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/picean/p8.png" />
                    </a>
                </div>
                <div style="clear:both;"></div>                
            </div>
           </div>
            <div style="text-align:center;padding:10px; font-size:14px;">
                <span>Prices stated does not include delivery charges of $8.56 per location</span>
            </div>
            <div class="edm-contact" style="width:100%;height:75px;text-align: center;">
                <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/edm_thankyou_contact.png" />
            </div>
            <div class="edm-footer" style=" margin-bottom: 30px;padding: 15px 50px 0px;text-align: center;font-size:15px;color: #231f20;">
                <div class="footer-bar" style=" border-bottom: 1px solid #231f20; padding-bottom: 8px;">
                    <a href="http://rosesonly.com.sg/customer/account/login/" style="color: #231f20; text-decoration: none;">Log in</a>
                    <span>|</span>
                    <a href="" style="color: #231f20; text-decoration: none;">Subscribe</a>
                    <span>|</span>
                    <a href="" style="color: #231f20; text-decoration: none;">Unsubscribe</a>
                    <span>|</span>
                    <a href="http://rosesonly.com.sg/privacy/" style="color: #231f20; text-decoration: none;">Terms & Conditions</a>
                </div>
                <div class="footer-bar2" style=" padding:5px 0px; font-size: 15px;">
                    <a href="http://rosesonly.com.sg/privacy/" style="color: #231f20;">Terms & Conditions apply</a>
                </div>
                <div class="footer-msg">Roses Only Asia Pte Ltd</div>
                <div class="footer-msg">You received this newsletter because you have registered with us and agreed to be contacted about our upcoming events and exclusive promotions.</div>
            </div>
        </td>
        <td width="210px" style="border: 0;"></td>
    </tr>
    <tr><td><div style="height:20px;"></div></td></tr>
</table>