<?php if(Mage::getStoreConfig('onestepcheckout/config/allowcoupon')):?>	
		<div id="tab-coupon">
			<?php echo $this->getChildHtml('coupon');?>
		</div>
<?php endif;?>
<?php if(Mage::getStoreConfig('onestepcheckout/config/enable_messagetosystem')):?>
<div class="onestepcheckout-comments">
		<label for="id_comments"><?php echo $this->__('Comments');?></label><br/>
		<textarea id="id_comments" name="onestepcheckout_comments" cols="40" rows="4"></textarea>
</div>
<?php endif;?>
<br>
<?php if(Mage::getStoreConfig('onestepcheckout/termcondition/allow_options')):?>
	<div class="onestepcheckout-enable-terms">
		<input class="required-entry" type="checkbox" id="id_accept_terms" name="accept_terms" value="1"  />
		<label for="id_accept_terms"><?php echo $this->__('I accept the');?> <a id="onestepcheckout-toc-link" target="_blank" href="#inline2"><?php echo $this->__('Terms and Conditions');?></a></label>
	</div>
<?php endif ?>