<?php $productIds = $this->getFreeCatalogGifts();?>
<?php if($productIds):?>
<div class="freegift_header"><h5><?php echo $this->__("Free gift")?></h5></div>
<div class="freegift_container clearer">
	<ul id="freegift" >
	<?php 
	foreach($productIds as $productId):?>
		<li>
			<?php $freegift = Mage::getModel('catalog/product')->load($productId); 	?>
			<a href="<?php echo $freegift->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($freegift, 'small_image')) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($freegift, 'small_image')->resize(75); ?>" width="75" height="75" alt="<?php echo $this->htmlEscape($this->getImageLabel($freegift, 'small_image')) ?>" /></a>          	
        	<h2 class="product-name"><a href="<?php echo $freegift->getProductUrl() ?>" title="<?php echo $this->htmlEscape($freegift->getName()) ?>"><?php echo $this->htmlEscape($freegift->getName())?></a></h2>                    
	     </li>		
	<?php endforeach ?> 	
	</ul>
	<div style="clear: both;"></div>
</div>
<?php endif;?>
