<?php if(version_compare(Mage::getVersion(),'1.4.0.1','>='))://fix cho magento 1.3?>
						<li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setTemplate('mw_onestepcheckout/name.phtml')->setObject($this->getAddress())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?></li>

                        <!-- add field -->
                        <li lang="fields">
                            <div class="field">
                                <label for="billing:company" class="required"><?php echo $this->__('Company') ?></label>
                                <div class="input-box">
                                    <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text inputtext" />
                                </div>
                            </div>

                            <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                            <div class="field">
                                <label for="billing:building-name" class="required"><?php echo $this->__('Building Name') ?></label>
                                <div class="input-box">
                                    <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i)) ?>" class="input-text inputtext" />
                                </div>
                            </div>
                            <?php endfor ?>
                        </li>

                        <li class="wide">
                            <div class="field">
                                <label for="billing:street1" class="required"><em>*</em><?php echo $this->__('Street Name') ?></label>
                                <div class="input-box">
                                    <input type="text" title="<?php echo $this->__('Street Name') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text inputtext required-entry" />
                                </div>
                            </div>
                        <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                            <div class="field block">
                                <label for="billing:street1"><?php echo $this->__('Block No.') ?></label>
                                <div class="input-box">
                                    <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i)) ?>" class="input-text-block inputtext" />
                                </div>
                            </div>
                        <?php endfor ?>
                        <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                            <div class="field unit">
                                <label for="billing:street1" ><?php echo $this->__('Unit No.') ?></label>
                                <div class="input-box">
                                    <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i)) ?>" class="input-text-unit inputtext" />
                                </div>
                            </div>
                        <?php endfor ?>
                        </li>
                        <li class="fields">
                            <div class="field">
                                <label for="billing:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                                <div class="input-box">
                                    <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="input-text inputtext required-entry" id="billing:city" />
                                </div>
                            </div>
                        </li>
                        <li class="fields">

                            <div class="field">
                                <label for="billing:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                                <div class="input-box">
                                    <?php echo $this->getCountryHtmlSelect('billing') ?>
                                </div>
                            </div>
                            <div class="field">
                                <label for="billing:postcode" class="required"><em>*</em><?php echo $this->__('Postal Code') ?></label>
                                <div class="input-box">
                                    <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="input-text inputtext validate-zip-international required-entry" />
                                </div>
                            </div>
                        </li>
                        <li class="fields">

                            <div class="field">
                                <label for="billing:telephone" class="required"><em>*</em><?php echo $this->__('Contact No.') ?></label>
                                <div class="input-box">
                                    <input type="text" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Contact No.') ?>" class="input-text inputtext required-entry" id="billing:telephone" />
                                </div>
                            </div>
                            <div class="field">
                                <label for="billing:telephone" class="required"><em>*</em><?php echo $this->__('Confirm Contact No.') ?></label>
                                <div class="input-box">
                                    <input type="text" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Confirm Contact No.') ?>" class="input-text inputtext required-entry" id="billing:telephone" />
                                </div>
                            </div>
                        </li>
                        <li class="fields">
                            <?php if(!$this->isCustomerLoggedIn()): ?>
                                <div class="field">
                                    <label for="billing:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                    <div class="input-box">
                                        <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text inputtext validate-email required-entry" />
                                    </div>
                                </div>
                            <?php endif ?>
                            <?php if(!$this->isCustomerLoggedIn()): ?>
                                <div class="field">
                                    <label for="billing:email" class="required"><em>*</em><?php echo $this->__('Confirm Email Address') ?></label>
                                    <div class="input-box">
                                        <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Confirm Email Address') ?>" class="input-text inputtext validate-email required-entry" />
                                    </div>
                                </div>
                            <?php endif ?>
                        </li>

                        <!-- end add field -->


<?php else:?>
					<li><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())
							->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?></li>
						<li><div class="input-box">
							<label for="billing:company"><?php echo $this->__('Company') ?></label><br />
							<input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" /></div>
				<?php if(!$this->isCustomerLoggedIn()): ?>
							<div class="input-box">
							<label for="billing:email"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label><br />
							<input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="validate-email required-entry input-text" /></div>
				<?php endif ?>
							</li>
						<li><label for="billing:street1"><?php echo $this->__('Address') ?> <span class="required">*</span></label><br />
							<input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="required-entry input-text" /></li>
				<?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
						<li><input type="text" title="<?php echo $this->__('Street Address '.$_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i)) ?>" class="input-text" /></li>
				<?php endfor ?>
						<li><div class="input-box">
							<label for="billing:city"><?php echo $this->__('City') ?> <span class="required">*</span><em>*</em></label><br />
							<input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="required-entry input-text" id="billing:city" /></div>
							<div class="input-box">
							<label for="billing:region"><?php echo $this->__('State/Province') ?> <span class="required"></span></label><br/>
							<select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none">
								<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
							</select>
							<script type="text/javascript">
								$('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
							</script>
							<input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none" />
							</div></li>
						<li><div class="input-box">
							<label for="billing:postcode"><?php echo $this->__('Zip/Postal Code') ?> <span class="required">*</span></label><br />
							<input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="validate-zip-international required-entry input-text" /></div>
							<div class="input-box">
								<label for="billing:country_id"><?php echo $this->__('Country') ?> <span class="required">*</span></label><br />
								<?php echo $this->getCountryHtmlSelect('billing') ?></div></li>
						<li><div class="input-box">
							<label for="billing:telephone"><?php echo $this->__('Telephone') ?> <span class="required">*</span></label><br/>
							<input type="text" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="required-entry input-text" id="billing:telephone" /></div>
							<div class="input-box">
							<label for="billing:fax"><?php echo $this->__('Fax') ?></label><br/>
							<input type="text" name="billing[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text" id="billing:fax" /></div></li>	
		
<?php endif;?>	
<script>
	$MW_Onestepcheckout(function(){
			/*$MW_Onestepcheckout("#billing\\:street1").css('width','262px');
			$MW_Onestepcheckout("#billing\\:street2").css('width','262px');*/
	});
	
	$MW_Onestepcheckout("#billing\\:vat_id").change(function(){
	updateShippingType();
    updateShippingMethod();
}); 
</script>