<?php $productIds = $this->getFreeProducts();

/* start check for rules */
$items = Mage::getSingleton('checkout/session')->getQuote()->getAllItems();
$arr = array();
//$arr_rule = array();
foreach($items as $item) {
    	$abc = $this->getRuleByFreeProductId($item->getProductId());
    	if($abc)
    		$arr[] = $abc->getId();
}
$str_pro = '';
//Zend_debug::dump($productIds);
foreach($productIds as $item1) {
	//$str_pro = '';
	$rule1 = $this->getRuleByFreeProductId($item1);
	if($rule1){
		if(!in_array($rule1->getId(),$arr))$str_pro.=$item1 . ',';
	}
}
$str_pro = substr($str_pro,0,strlen($str_pro)-1);
if($str_pro) $productIds = explode(",", $str_pro);
?>
<?php if($productIds):?>
<script type="text/javascript">
/*<![CDATA[*/
function mycarousel_initCallback(carousel)
{
    // Disable autoscrolling if the user clicks the prev or next button.
    carousel.buttonNext.bind('click', function() {
        carousel.startAuto(0);
    });
    carousel.buttonPrev.bind('click', function() {
        carousel.startAuto(0);
    });
    // Pause autoscrolling if the user moves with the cursor over the clip.
    carousel.clip.hover(function() {
        carousel.stopAuto();
    }, function() {
        carousel.startAuto();
    });
};

$xmage_freegift(document).ready(function() {
	$xmage_freegift('#freegift').jcarousel({
	   	//auto: 2,
	    wrap: 'last',
	    initCallback: mycarousel_initCallback,
	    visible:6,
	    vertical: false
    });
});
/*]]>*/
</script>

<ul id="freegift" class="jcarousel-skin-tango" >
<?php 
if(sizeof($productIds) == 1)
{
	echo "
				<script language='javascript'>
						document.getElementById('btn1').click();
				</script>";
}

foreach($productIds as $productId):
?>
	<?php $product = Mage::getModel('catalog/product')->load($productId)?>
	<li>
	<a href="<?php echo $product->getProductUrl().'?mw_freegift=1'; ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(85); ?>" width="85" height="85" alt="<?php echo $this->htmlEscape($this->getImageLabel($product, 'small_image')) ?>" /></a>
			<div class="product-shop">
                <div class="f-fix">                	
                    <h2 class="product-name"><a href="<?php echo $product->getProductUrl().'?mw_freegift=1'; ?>" title="<?php echo $this->htmlEscape($product->getName()) ?>"><?php echo $this->htmlEscape($product->getName())?></a></h2>
                    <div class="old-price">
                    	<?php echo $this->getPriceHtml($product, true) ?>
                    </div>
                    <?php if($product->isSaleable()): ?>
                    	<?php $rule = $this->getRuleByFreeProductId($productId);?>
                    	<?php if($rule): $url = $this->getAddToCartUrl($product,array('freegift'=>1,'apllied_rule'=>$rule->getId()));?>
                    	<?php $mw_class_rule = 'mw_rule'.$rule->getId();?>
                    	<?php else:$url = $this->getAddToCartUrl($product,array('freegift'=>1));?>
                    	<?php $mw_class_rule = 'mw_rule';?>
                    	<?php endif;?>
                        <p><button id="btn1" type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart <?php echo $mw_class_rule;?>" onclick="mw_disableRule(this.className);setLocation('<?php echo $url;?>');"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>
            </div>
            <div class="free-icon"></div>
     </li>		
<?php endforeach ?> 	
</ul>
<?php endif;?>

<script type="text/javascript">
//<![CDATA[

function mw_disableRule(strId)
{
	var id = strId.split(' ');
 	var classrule = '.'+id[2];
	if($$(classrule))  $$(classrule).invoke('setStyle', { display:'none'}); 
}

//]]>
</script>