<!--<script type='text/javascript'>-->
<!--    rtgsettings = {-->
<!--        'pdt_id': '$pdt_id$',-->
<!--        'pdt_url': '$pdt_url$',-->
<!--        'ty_orderid': '$ty_orderid$',-->
<!--        'ty_orderamt': '$ty_orderamt$',-->
<!--        'ty_orderdate': '$ty_orderdate$',-->
<!--        'ty_orderstatus': '$ty_orderstatus$',-->
<!--        'ty_cusname': '$ty_cusname$',-->
<!--        'ty_cusid': '$ty_cusid$',-->
<!--        'ty_custype': '$ty_custype$',-->
<!--        'key': 'AG',-->
<!--        'token': 'RoseOnly_SG',-->
<!--        'pagetype': 'basket',-->
<!--        'layer': 'iframe'-->
<!--    };-->
<!--    (function (d) {-->
<!--        var s = d.createElement('script');-->
<!--        s.async = true;-->
<!--        s.id = 'madv2014rtg';-->
<!--        s.type = 'text/javascript';-->
<!--        s.src = (d.location.protocol == 'https:' ? 'https:' : 'http:') + '//www.mainadv.com/Visibility/Rtgag2-min.js';-->
<!--        var a = d.getElementsByTagName('script')[0];-->
<!--        a.parentNode.insertBefore(s, a);-->
<!--    }(document));-->
<!--</script>-->

<script type="text/javascript">

    <?php
    $session = Mage::getSingleton('core/session');
    $delivery_date = $session->getData('_deliverydate');
    $delivery_time = $session->getData('onestepcheckout_time');



    if($delivery_date==null){
        ?>
    var date = readCookie('delivery_date');
    var time = readCookie('delivery_time');
    <?php }else {?>
    var date = '<?php echo $delivery_date;?>';
    var time = '<?php echo $delivery_time;?>';
    <?php }?>
    <?php
    $delivery_date_time = $delivery_date . "                             " . $delivery_time;
    $_SESSION['delivery_date_time'] = $delivery_date_time;
    ?>

</script>

<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
if ($_COOKIE['delivery_cost'] != '')
    $shippingcost = $_COOKIE['delivery_cost'];
else if (Mage::getStoreConfig("onestepcheckout/config/default_shippingcost"))
    $shippingcost = Mage::getStoreConfig("onestepcheckout/config/default_shippingcost");
?>
<div class="cart">
    <div class="shopping-cart-name"><h1><?php echo $this->__('Secure Checkout') ?>
            <?php //echo $delivery_date_time; ?>
        </h1></div>
    <!--<div class="cart-progress-block">-->
    <div class="top_checkout">
        <ul class="checkoutsteps">
            <li id="step1" class="current"><span class="step_number">1</span><a
                    href="<?php echo $this->getUrl('checkout/cart') ?>">Shopping Cart</a></li>
            <li id="step2"><span class="step_number">2</span><a href="javascript:void(0);">Recipient Information</a>
            </li>
            <li id="step3"><span class="step_number">3</span><a href="javascript:void(0);">Review & Place Order</a></li>
        </ul>
    </div>


    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
        <fieldset>
            <table id="shopping-cart-table" class="data-table cart-table">
                <col width="1"/>
                <col/>
                <!--<col width="1" />-->
                <!--?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                    <col width="1" />
                <--?php endif ?-->
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1"/>
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1"/>
                <?php endif; ?>
                <col width="1"/>
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1"/>
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1"/>
                <?php endif; ?>
                <col width="70"/>
                <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>

                <div id="title-cart" style="display: none"><h1>Shopping Cart</h1></div>

                <thead id="title-cart-detail">

                <tr>
                    <th class="head-first" rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
                    <th rowspan="<?php echo $mergedCells; ?>"
                        style="font-weight:normal"><?php echo $this->__('Product Name') ?></th>
                    <th class="a-center" colspan="<?php echo $mergedCells; ?>"
                        style="font-weight:normal"><?php echo $this->__('Delivery Date & Time') ?></th>
                    <!--th rowspan="<?php echo $mergedCells; ?>"></th-->
                    <!--?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                        <th rowspan="<-?php echo $mergedCells; ?>" class="a-center"><span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span></th>
                        <-?php endif ?-->
                    <th class="a-center" colspan="<?php echo $mergedCells; ?>"
                        style="font-weight:normal"><?php echo $this->__('Unit Price') ?></th>
                    <th rowspan="<?php echo $mergedCells; ?>" class="a-center"
                        style="font-weight:normal"><?php echo $this->__('Qty') ?></th>
                    <th class="a-center" colspan="<?php echo $mergedCells; ?>"
                        style="font-weight:normal"><?php echo $this->__('Subtotal') ?>
                        <span><?php //echo $this->__('(w/gst)') ?></span></th>
                    <th rowspan="<?php echo $mergedCells; ?>" class="a-center last">&nbsp;</th>
                </tr>
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <tr>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    </tr>
                <?php endif; ?>
                </thead>
                <tfoot>
                <tr>
                    <td colspan="50" class="a-right">
                        <?php if ($this->getContinueShoppingUrl()): ?>
                            <button type="button" title="<?php echo $this->__('Continue Shopping') ?>"
                                    class="button btn-continue"
                                    onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')">
                                <span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                        <?php endif; ?>
                        <button type="submit" name="update_cart_action" value="update_qty"
                                title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update">
                            <span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
                        <button type="submit" name="update_cart_action" value="empty_cart"
                                title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="button btn-empty"
                                id="empty_cart_button">
                            <span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
                        <!--[if lt IE 8]>
                        <input type="hidden" id="update_cart_action_container"/>
                        <script type="text/javascript">
                            //<![CDATA[
                                Event.observe(window, 'load', function()
                                {
                                    // Internet Explorer (lt 8) does not support value attribute in button elements
                                    $emptyCartButton = $('empty_cart_button');
                                    $cartActionContainer = $('update_cart_action_container');
                                    if ($emptyCartButton && $cartActionContainer) {
                                        Event.observe($emptyCartButton, 'click', function()
                                        {
                                            $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                            $cartActionContainer.setAttribute('name', 'update_cart_action');
                                            $cartActionContainer.setValue('empty_cart');
                                        });
                                    }

                                });
                            //]]>
                            </script>
                            <![endif]-->
                    </td>
                </tr>
                </tfoot>
                <tbody>
                <?php foreach ($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
            </table>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
        </fieldset>
    </form>
    <div class="cart-collaterals">
        <div class="coupon">
            <div class="col-1">
                <?php echo $this->getChildHtml('crosssell') ?>
            </div>
            <div class="col-2">
                <?php /* Extensions placeholder */ ?>
                <?php echo $this->getChildHtml('checkout.cart.extra') ?>
                <?php echo $this->getChildHtml('coupon') ?>
                <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping');
                endif; ?>
            </div>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('shopping-cart-bottom')->toHtml(); ?>
        </div>
        <?php /*?><div class="checkout-enquiries">
            <label>For enquires, contact us!</label>
            <p class="footer-email">info.sg@rosesonlyasia.com</p>
            <p class="footer-phone">(65) 6256 1818</p>
            <p class="footer-fax">(65) 6256 1612</p>
        </div><?php */ ?>
        <div class="totals">
            <?php echo $this->getChildHtml('totals'); ?>
            <?php if (!$this->hasError()): ?>
                <ul class="checkout-types">
                    <?php foreach ($this->getMethods('methods') as $method): ?>
                        <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                            <li><?php echo $methodHtml; ?></li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
    </div>
</div>


<script type="text/javascript">
    function m_updatePrice() {

        //alert('update');

        var subtotal = document.getElementById("subtotal");
        var discount = document.getElementById("discount");
        if (readCookie('shipping_cost').length > 0)
            var delivery = Number(readCookie('shipping_cost').replace(/[^0-9\.]+/g, ""));
        else var delivery = <?php echo $shippingcost; ?>;
        var numdiscount = 0;

        if (discount != null)
            numdiscount = Number(discount.value);

        //var total = Math.round((Number(subtotal.value)+ delivery + numdiscount)*100)/100;
        var total = Math.round((Number(subtotal.value) + numdiscount) * 100) / 100;

        var price = document.querySelectorAll(".checkout-total td.lasttotal .price");
        if (price != null && price.length > 0) {
            //alert(total);
            for (var i = 0; i < price.length; i++) {
                price[i].innerHTML = "<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . ''; ?>"
                + total;
            }
        }
    }



</script>

<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery(".<?php echo $_SESSION['current_product_name']; ?>").html("<?php echo $_SESSION['delivery_date_time']; ?>");
        jQuery(".<?php echo $_SESSION['current_product_name']; ?>").attr('readonly','readonly')
        if(jQuery("ul li").hasClass("success-msg")){
             setTimeout(function(){ jQuery("button.btn-update").click(); }, 500);
        }
    });

</script>
