<?php
/*
 * Copyright (C) 2012 Clearspring Technologies, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>
<SCRIPT TYPE="text/javascript">
   
    function popup(mylink, windowname)
    {
        var width=600;
        var height=350;
        var left = (screen.width/2)-(width/2);
        var top = (screen.height/2)-(height/2);
        
        
        if (! window.focus)return true;
        var href;
        if (typeof(mylink) == 'string')
            href=mylink;
        else
            href=mylink.href;
        window.open(href, windowname, 
        'width='+width+',height='+height+',top='+top+',left='+left+',scrollbars=yes');
        return false;
    }
    
</SCRIPT>
<?php
/* * General Options */
$plugin_enabled = $this->getPluginEnabledStatus();
$pubid = $this->getPubId();

/* * Custom Share */
$custom_url = $this->getCustomUrl();
$custom_title = $this->getCustomTitle();
$custom_description = $this->getCustomDescription();
$custom_share = "addthis:url='" . $custom_url . "' addthis:title='" . $custom_title . "' addthis:description='" . $custom_description . "'";

/* * API COnfig Options */
$services_exclude = $this->getExcludeServices();
$services_compact = $this->getCompactServices();
$services_expanded = $this->getExpandedServices();
$ui_click = $this->getUiClick();
$ui_delay = $this->getUiDelay();
$ui_hover_direction = $this->getUiHover();
$ui_open_windows = $this->getUiOpenWindows();
$ui_language = $this->getUiLanguage();
$ui_offset_top = $this->getUiOffsetTop();
$ui_offset_left = $this->getUiOffsetLeft();
$ui_cobrand = $this->getUiCobrand();
$ui_use_css = $this->getUiCss();
$ui_use_addressbook = $this->getUiAddressBook();
$ui_508_compliant = $this->getUiCompliant();
$data_track_clickback = $this->getDataTrackClick();
$address_bar_share = $this->getAddressBarShare();
$data_ga_tracker = $this->getDataGaTracker();


/* * Custom Service */
$services_custom_name = $this->getCustomServiceName();
$services_custom_url = $this->getCustomServiceUrl();
$services_custom_icon = $this->getCustomServiceIcon();
?>
<!-- Check whether the plugin is enabled -->
<?php
if ($plugin_enabled != 0):
    ?>

    <!-- AddThis Button BEGIN -->

    <!-- AddThis API Config -->

    <script type='text/javascript'>
        var addthis_product = 'mag-1.0';
        var addthis_config 	= {
    <?php
    if ($pubid):
        echo "pubid : '" . $pubid . "'\n";
    else:
        echo "pubid : 'unknown'\n";
    endif;
    if ($services_exclude):
        echo ", services_exclude : '" . $services_exclude . "'\n";
    endif;
    if ($services_compact):
        echo ", services_compact : '" . $services_compact . "'\n";
    endif;
    if ($services_expanded):
        echo ", services_expanded : '" . $services_expanded . "'\n";
    endif;
    if ($services_custom_name && $services_custom_url):
        echo ", services_custom : { name:'" . $services_custom_name . "', url:'" . $services_custom_url . "', icon:'" . $services_custom_icon . "' }\n";
    endif;
    if ($ui_click == 0):
        echo ", ui_click : true \n";
    endif;
    if ($ui_delay):
        echo ", ui_delay : '" . $ui_delay . "'\n";
    endif;
    if ($ui_hover_direction != 0):
        echo ", ui_hover_direction : '" . $ui_hover_direction . "'\n";
    endif;
    if ($ui_open_windows == 1):
        echo ", ui_open_windows : true \n";
    endif;
    if ($ui_language != 'auto'):
        echo ", ui_language : '" . $ui_language . "'\n";
    endif;
    if ($ui_offset_top):
        echo ", ui_offset_top : " . $ui_offset_top . "\n";
    endif;
    if ($ui_offset_left):
        echo ", ui_offset_left : " . $ui_offset_left . "\n";
    endif;
    if ($ui_cobrand):
        echo ", ui_cobrand : '" . $ui_cobrand . "'\n";
    endif;
    if ($ui_use_css == 0):
        echo ", ui_use_css : false \n";
    endif;
    if ($ui_use_addressbook == 1):
        echo ", ui_use_addressbook : true \n";
    endif;
    if ($ui_508_compliant == 1):
        echo ", ui_508_compliant : true \n";
    endif;
    if ($data_track_clickback == 0):
        echo ", data_track_clickback : false \n";
    endif;
    if ($address_bar_share == 1):
        echo ", data_track_addressbar : true \n";
    endif;
    if ($data_ga_tracker):
        echo ", data_ga_tracker : '" . $data_ga_tracker . "'\n";
    endif;
    ?>

        }
    </script>
    <!-- AddThis API Config END -->

    <div style="float: left;" class="addthis_toolbox addthis_default_style " <?php echo $custom_share ?>>
        <h3>Share the joy!</h3>
        <table style="color:#736b6d;" width = "120px" height="100px">
            <tr>
                <td style="" >Like</td>
                <td style="padding-left:10px;">
                    <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
                </td>
            </tr>
            <tr >
                <td style=""> Share</td>
                <td style="padding-left:10px;"> 
                    <?php $currUrl = $this->getUrl('') . $_SERVER['REQUEST_URI']; ?>
                    <a class="button_facebook at300b" 
                       onclick="return popup(this, 'Facebook share');" name="fb_share" 
                       type="icon" 
                       href="http://www.facebook.com/sharer.php?u=<?php echo $currUrl;?>" ><span class="at300bs"></span></a>
    <!--script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script-->
                    <!--a onclick="return popup(this, 'Facebook share');" class="addthis_button_facebook"></a-->
                    <a class="addthis_button_twitter"></a>
                    <a class="addthis_button_pinterest_share"></a>
                </td>
            </tr>
            <tr >
                <td style="padding-top:10px;"> Email</td>
                <td style="padding-top:10px;padding-left:10px;">
                    <a class="addthis_button_email"></a>
                </td>
            </tr>
            <tr style="padding-top:10px;">
                <td style="padding-top:10px;"> Print</td>
                <td style=padding-top:10px;padding-left:10px;">
                    <a class="addthis_button_print"></a>
                </td>
            </tr>
        </table>
    </div>
    <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4f0c254f1302adf8"></script>
    <!-- AddThis Button END -->
    <?php
endif; //if plugin not enabled
?>