<?php 
/**
 * Yumba Soft
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Yumba
 * @package    Yumba_OrderCancel
 * @copyright  Copyright (c) 2011 Yumba Soft (yumba.soft@gmail.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="account-box ad-orders">
<?php $_orders = $this->getOrders(); ?>
    <div class="head">
        <h4><?php echo $this->__('Recent Orders') ?></h4>
        <?php if( sizeof($_orders->getItems()) > 0 ): ?><a href="<?php echo $this->getUrl('sales/order/history') ?>"><?php echo $this->__('View All') ?></a><?php endif; ?>
    </div>
<?php if( sizeof($_orders->getItems()) > 0 ): ?>
    <table cellspacing="0" class="data-table" id="my-orders-table">
        <thead>
            <tr>
                <th><?php echo $this->__('Order #') ?></th>
                <th><?php echo $this->__('Date') ?></th>
                <!-- <th><?php echo $this->__('Ship to') ?></th> -->
                <th><?php echo $this->__('Order Total') ?></th>
                <th><?php echo $this->__('Status') ?></th>
                <th class="last"></th>
            </tr>
        </thead>
        <tbody>
        <?php $_odd = ''; ?>
            <?php foreach ($_orders as $_order): ?>
                <tr class="<?php echo ($_odd = ($_odd ? 'odd' : '')) ?>">
                    <td><?php echo $_order->getRealOrderId() ?>&nbsp;</td>
                    <td><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?> </td>
                    <!-- <td><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '' ?>&nbsp;</td> -->
                    <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?>&nbsp;</td>
                    <td><em><?php echo $_order->getStatusLabel() ?></em>&nbsp;</td>
                    <td class="last a-center"><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View Order') ?></a>
                        <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                            <span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" style="font-weight: bold; color: #403A3A;"><?php echo $this->__('Reorder') ?></a>
                        <?php endif ?>
                        <?php /* CHANGES STARTS */ ?>
                        <!--?php if ($_order->canCancel()) { ?>
                            <span class="separator">|</span> 
                            <a class="order-cancel" href="< ?php echo $this->getUrl('ordercancel/order/cancel', array('order_id' => $_order->getId())); ?>">
                                < ?php echo $this->__('Cancel') ?>
                            </a>
                        < ?php } ?-->
                        	
                    	<?php /* CHANGES ENDS */ ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif; ?>
</div>