<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output'); $addon4 = 1;
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="addon_products overflowclear" id="products_addon">
        <?php if($this->getMode()!='grid'): ?>
        <?php else: ?>
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = 4; ?>
        <?php $i=0; foreach ($_productCollection as $_product): $addon4++; ?>
        <?php if ($i++%$_columnCount==0): ?>
            <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(116); ?>" width="116" height="116" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <div class="checkbox_and_price">
                    <input type="radio" name="add_on_group2"  class="f-left radio_button_product" id="<?php echo "addon4" . $addon4; ?>" value="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>" />
                    <label for="<?php echo "addon4" . $addon4; ?>">
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    </label>
                </div>
                <h2 class="product-name">
                    <label><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></label>
                </h2>
            </li>
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            </ul>
        <?php endif ?>
        <?php endforeach ?>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <?php endif; ?>
    </div>
<?php endif; ?>
