<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
    <head>
        <title>Roes Only Singapore</title>
        <link rel="icon" href="http://rosesonly.com.sg/media/favicon/default/Fab_1.jpg" type="image/x-icon"/>
        <link rel="shortcut icon" href="http://rosesonly.com.sg/media/favicon/default/Fab_1.jpg" type="image/x-icon"/>
    </head>
    <body style="margin: 0; font-family: Calibri;">      
        <?php echo $this->getChildHtml('content') ?> 
    </body>
</html>
