<!DOCTYPE html>
<html>
<head>
<link rel="icon" href="http://rosesonly.com.sg/media/favicon/default/favicon_1.ico" type="image/x-icon">
<link rel="shortcut icon" href="http://rosesonly.com.sg/media/favicon/default/favicon_1.ico" type="image/x-icon">
<title>Online Flowers Delivery - Flower, Roses & Gifts by Roses Only</title>
<style type="text/css">
body{
    margin: 0px;
}
.content{
    padding-top: 10px;
    width: 902px;
    margin: auto;
}
.header{
    background-color: #FFFFFF;
    height: 115px;
    width: 100%;
}
.header_left{
    float: left;
    margin-top: 10px;
    height: 115px;
}
.header_right{
    float: right;
    margin-right: 20px;
    text-align: right;
    height: 115px;
    font-size: 13px;
}
.header_right p{
    color: #696969;
    font-weight: 600;
}
.header_right a{
    color: #b8b8b8;
}

.tender_love{
    background: url(http://rosesonly.com.sg/skin/frontend/default/f002/special/mother_2014/tender-love.png) no-repeat;
    width: 835px;
    height: 290px;
    margin: auto;
    padding-left: 10px;
    padding-top: 40px;
}
.delightful_love{
    background: url(http://rosesonly.com.sg/skin/frontend/default/f002/special/mother_2014/delightful-love.png) no-repeat;
    float: left;
    height: 835px;
    padding-left: 10px;
    padding-top: 60px;
    width: 200px;
    margin-left: 30px;
}

.wholesome_love{
    background: url(http://rosesonly.com.sg/skin/frontend/default/f002/special/mother_2014/wholesome-love.png) no-repeat;
    float: left;
    height: 835px;
    padding-left: 10px;
    padding-top: 60px;
    width: 200px;
}

.soothing_love{
    background: url(http://rosesonly.com.sg/skin/frontend/default/f002/special/mother_2014/soothing-love.png) no-repeat;
    float: left;
    height: 577px;
    padding-left: 10px;
    padding-top: 70px;
    width: 200px;
    margin-top: 18px;
}

.gracious_love{
    background: url(http://rosesonly.com.sg/skin/frontend/default/f002/special/mother_2014/gracious-love.png) no-repeat;
    float: right;
    height: 577px;
    padding-left: 10px;
    padding-top: 70px;
    width: 200px;
    margin-right: 27px;
    margin-top: 18px;
}
.tender_love table{
    width: 850px;
}
.info{
    text-align: center;
    display: inline;
    margin: auto;
}
.info p{
    margin-top: 0px;
}
.left{
    font-size: 10px;
    float: left;
    padding-bottom: 10px;
    /*padding-top: 5px;*/
    width: 80%;
}
.right{
    width:40px;
    height:40px;
    /*margin-top: 5px;*/
    border-radius:20px;
    line-height: 40px;
    text-align: center;
    font-size: 12px;
    /*padding-right: 30px;*/
    color: #ffffff;
}
.padding_right{
    margin-right: 30px;
}
.even{
    background: #eb698a;
}
.odd{
    background: #d33259;
}
.img-header{
    text-align: left;
    float: left;
    height: 445px;
}

.footer-info{
    width: 815px;
    margin: auto;
    background-color: #fee6ec;
    padding: 15px 10px 10px 10px;
    display: block;
    text-align: center;
    font-size: 11px;
}
.footer{
    margin-top: 20px;
}
.footer-info a{
    font-size: 11px;
    color: #696969;
    text-decoration: none;
    padding: 4px;
    font-weight: bold;
}
.product{
    height: 1200px;
    margin-top: 33px;
}
.label-payment {
    padding-bottom: 10px;
    padding-top: 15px;
}
.label-payment span{
    font-size: 11px;
    color: #696969;
    font-weight: bold;
}
.footer-payment {
    background: url(http://rosesonly.com.sg/skin/frontend/default/f002/images/i-payment.png);
    background-repeat: no-repeat;
    height: 22px;
    width: 124px;
    margin: auto;
}
.footer-container{
    width: 860px;
    margin: auto;
    text-align: center;
    font-weight: bold;
    padding-top: 10px;
}
.footer-container p{
    font-size: 10px;
    color: #696969;
    margin-bottom: 0px;
}
del{
    font-weight: bold;
    /*font-size: 11px;*/
}
.new_price{
    font-size: 12px;
    color: #b72226;
    font-weight: bold;
}
.tender_love img, .delightful_love img, .wholesome_love img, .gracious_love img, .soothing_love img {
    border: 1px solid #E4E4E4;
}
.prd_info{
    width: 170px;
}
.buy{
    width: 20%;
    float: left;
}
.buy a{
    text-decoration: none;
}

.delightful_love tr, .wholesome_love tr, .soothing_love tr, .gracious_love tr{
    height: 81px;
}

.tender_love td, .delightful_love td, .wholesome_love td, .soothing_love td, .gracious_love td{
    vertical-align: top;
}

.product a{
    color: black;
    text-decoration: none;
}
</style>
</head>
<body style="background: url('http://rosesonly.com.sg/skin/frontend/default/f002/special/mother_2014/bgr2.png'); font-family: Helvetica;">

<?php
$product_ids = array(
    //tender love
    "551", "553", "552", "554",
    //delightful
    "555", "557", "558",
    // wholesome
    "559", "556", "561",
    // soothing
    "563", "564",
    // gracious
    "566", "567"
);
?>

<div class="content">
    <div class="header">
        <div class="header_left">
            <a href="http://rosesonly.com.sg/"><img style="float: left;" src="http://rosesonly.com.sg/skin/frontend/default/f002/special/mother_2014/logo.png" /></a>
        </div>
        <div class="header_right">
            <p>Singapore Wide Delivery Call: (65) 6256 1818</br>
                Fax: (65) 6256 1612
            </p>
            <p>Mon to Fri 9.00am to 7.00pm</p>
            <p><a href="http://rosesonly.com.sg/homepage">You are viewing Mother's Day Gift Range. To view our normal range, click here</a></p>
        </div>

    </div>
    <div class="container" style="background: url('http://rosesonly.com.sg/skin/frontend/default/f002/special/mother_2014/bgr-container.png');min-height:1820px;">
        <div class="img-header">
            <table style=" margin-top: -15px; ">
                <tr>
                    <td><img src="http://rosesonly.com.sg/skin/frontend/default/f002/special/mother_2014/banner1.png" style=" margin-left: -5px; "/></td>
                    <td><img src="http://rosesonly.com.sg/skin/frontend/default/f002/special/mother_2014/banner2.jpg" style=" margin-left: -3px; "/>
                        <img src="http://rosesonly.com.sg/skin/frontend/default/f002/special/mother_2014/banner3.jpg" style=" margin-top: -5px; margin-left: -3px;"/></td>
                </tr>
            </table>
        </div>
        <div class="info">
            <p><strong>With Love on Mother's Day</strong> (14 Apr - 11 May 2014)</p>
            <p style="font-size: 14px;line-height: 1.4;"> Surprise Moms with the Best Roses in Singapore.</br>
                Let Roses Only Singapore deliver your Mother's Day gifts to thank them for being the best always.</p>
        </div>
        <div class="product">
            <div class="tender_love">
                <table>
                    <tr>
                    <?php $_product = Mage::getModel('catalog/product')->load($product_ids[0]); ?>
                        <td><a href="http://rosesonly.com.sg/occasion/mother-s-day/single-pink-rose-tender-love-gift-box.html"><img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(175,175);?>" /></a></td>
                        <?php $_product = Mage::getModel('catalog/product')->load($product_ids[1]); ?>
                        <td><a href="http://rosesonly.com.sg/occasion/mother-s-day/6-pink-roses-tender-love-gift-box.html"><img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(175,175);?>" /></a></td>
                        <?php $_product = Mage::getModel('catalog/product')->load($product_ids[2]); ?>
                        <td><a href="http://rosesonly.com.sg/occasion/mother-s-day/12-pink-roses-tender-love-gift-box.html"><img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(175,175);?>" /></a></td>
                        <?php $_product = Mage::getModel('catalog/product')->load($product_ids[3]); ?>
                        <td><a href="http://rosesonly.com.sg/occasion/mother-s-day/24-pink-roses-tender-love-gift-box.html"><img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(175,175);?>" /></a></td>
                    </tr>
                    <tr>
                        <td><div class="prd_info"><div class="left"><a href="http://rosesonly.com.sg/occasion/mother-s-day/single-pink-rose-tender-love-gift-box.html">Single Pink Rose
                                    Tender Love Gift Box</a></br>
                                    <del>$39.00</del><span class="new_price"> $35.10</span></div>
                                <div class="buy"><a href="http://rosesonly.com.sg/occasion/mother-s-day/single-pink-rose-tender-love-gift-box.html"><div class="right padding_right even"> BUY</div></a></div></div></td>
                        <td><div class="prd_info"><div class="left"><a href="http://rosesonly.com.sg/occasion/mother-s-day/6-pink-roses-tender-love-gift-box.html">6 Pink Roses
                                    Tender Love Gift Box</a></br>
                                    <del>$69.00</del><span class="new_price"> $62.10</span></div>
                                <div class="buy"><a href="http://rosesonly.com.sg/occasion/mother-s-day/6-pink-roses-tender-love-gift-box.html"><div class="right padding_right even"> BUY</div></a></div></div></td>
                        <td><div class="prd_info"><div class="left"><a href="http://rosesonly.com.sg/occasion/mother-s-day/12-pink-roses-tender-love-gift-box.html">12 Pink Roses
                                    Tender Love Gift Box</a></br>
                                    <del>$109.00</del><span class="new_price"> $98.10</span></div>
                                <div class="buy"><a href="http://rosesonly.com.sg/occasion/mother-s-day/12-pink-roses-tender-love-gift-box.html"><div class="right padding_right even"> BUY</div></a></div></div></td>
                        <td><div class="prd_info"><div class="left"><a href="http://rosesonly.com.sg/occasion/mother-s-day/24-pink-roses-tender-love-gift-box.html">24 Pink Roses
                                    Tender Love Gift Box</a></br>
                                    <del>$188.00</del><span class="new_price"> $169.20</span></div>
                                <div class="buy"><a href="http://rosesonly.com.sg/occasion/mother-s-day/24-pink-roses-tender-love-gift-box.html"><div class="right padding_right even"> BUY</div></a></div></div></td>
                    </tr>
                </table>
            </div>
            <div class="delightful_love">
                <table>
                    <?php $_product = Mage::getModel('catalog/product')->load($product_ids[4]); ?>
                    <tr>
                        <td><a href="http://rosesonly.com.sg/occasion/mother-s-day/6-pink-roses-delightful-love-gift-box-with-chocolate.html"><img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(175,175);?>" /></a></td>
                    </tr>
                    <tr><td><div class="prd_info"><div class="left"><a href="http://rosesonly.com.sg/occasion/mother-s-day/6-pink-roses-delightful-love-gift-box-with-chocolate.html">6 Pink Roses
                                    Delightful Love Gift Box
                                    with Chocolate</a></br>
                                    <del>$89.00</del><span class="new_price"> $80.10</span></div>
                                <div class="buy"><a href="http://rosesonly.com.sg/occasion/mother-s-day/6-pink-roses-delightful-love-gift-box-with-chocolate.html"><div class="right odd"> BUY</div></a></div></div></td>
                    </tr>
                    <?php $_product = Mage::getModel('catalog/product')->load($product_ids[5]); ?>
                    <tr>
                        <td><a href="http://rosesonly.com.sg/occasion/mother-s-day/12-pink-roses-delightful-love-gift-box-with-chocolate.html"><img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(175,175);?>" /></a></td>
                    </tr>
                    <tr><td><div class="prd_info"><div class="left"><a href="http://rosesonly.com.sg/occasion/mother-s-day/12-pink-roses-delightful-love-gift-box-with-chocolate.html">12 Pink Roses
                                    Delightful Love Gift Box
                                    with Chocolate</a></br>
                                    <del>$129.00</del><span class="new_price"> $116.10</span></div>
                                <div class="buy"><a href="http://rosesonly.com.sg/occasion/mother-s-day/12-pink-roses-delightful-love-gift-box-with-chocolate.html"><div class="right odd"> BUY</div></a></div></div></td>
                    </tr>
                    <?php $_product = Mage::getModel('catalog/product')->load($product_ids[6]); ?>
                    <tr>
                        <td><a href="http://rosesonly.com.sg/occasion/mother-s-day/24-pink-roses-delightful-love-gift-box-with-chocolate.html"><img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(175,175);?>" /></a></td>
                    </tr>
                    <tr><td><div class="prd_info"><div class="left"><a href="http://rosesonly.com.sg/occasion/mother-s-day/24-pink-roses-delightful-love-gift-box-with-chocolate.html">24 Pink Roses
                                    Delightful Love Gift Box
                                    with Chocolate</a></br>
                                    <del>$200.00</del><span class="new_price"> $187.20</span></div>
                                <div class="buy"><a href="http://rosesonly.com.sg/occasion/mother-s-day/24-pink-roses-delightful-love-gift-box-with-chocolate.html"><div class="right odd"> BUY</div></a></div></div></td>
                    </tr>
                </table>
            </div>
            <div class="wholesome_love">
                <table>
                    <?php $_product = Mage::getModel('catalog/product')->load($product_ids[7]); ?>
                    <tr>
                        <td><a href="http://rosesonly.com.sg/occasion/mother-s-day/6-pink-roses-wholesome-love-gift-box-with-dom-37-5cl.html"><img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(175,175);?>" /></a></td>
                    </tr>
                    <tr><td><div class="prd_info"><div class="left"><a href="http://rosesonly.com.sg/occasion/mother-s-day/6-pink-roses-wholesome-love-gift-box-with-dom-37-5cl.html">6 Pink Roses
                                    Wholesome Love Gift Box
                                    with DOM 37.5cl</a></br>
                                    <del>$129.00</del><span class="new_price"> $116.10</span></div>
                                <div class="buy"><a href="http://rosesonly.com.sg/occasion/mother-s-day/6-pink-roses-wholesome-love-gift-box-with-dom-37-5cl.html"><div class="right odd"> BUY</div></a></div></div></td>
                    </tr>
                    <?php $_product = Mage::getModel('catalog/product')->load($product_ids[8]); ?>
                    <tr>
                        <td><a href="http://rosesonly.com.sg/occasion/mother-s-day/12-pink-roses-wholesome-love-gift-box-with-dom-37-5cl.html"><img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(175,175);?>" /></a></td>
                    </tr>
                    <tr><td><div class="prd_info"><div class="left"><a href="http://rosesonly.com.sg/occasion/mother-s-day/12-pink-roses-wholesome-love-gift-box-with-dom-37-5cl.html">12 Pink Roses
                                    Wholesome Love Gift Box
                                    with DOM 37.5cl</a></br>
                                    <del>$169.00</del><span class="new_price"> $152.10</span></div>
                                <div class="buy"><a href="http://rosesonly.com.sg/occasion/mother-s-day/12-pink-roses-wholesome-love-gift-box-with-dom-37-5cl.html"><div class="right odd"> BUY</div></a></div></div></td>
                    </tr>
                    <?php $_product = Mage::getModel('catalog/product')->load($product_ids[9]); ?>
                    <tr>
                        <td><a href="http://rosesonly.com.sg/occasion/mother-s-day/24-pink-roses-wholesome-love-gift-box-with-dom-37-5cl.html"><img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(175,175);?>" /></a></td>
                    </tr>
                    <tr><td><div class="prd_info"><div class="left"><a href="http://rosesonly.com.sg/occasion/mother-s-day/24-pink-roses-wholesome-love-gift-box-with-dom-37-5cl.html">24 Pink Roses
                                    Wholesome Love Gift Box
                                    with DOM 37.5cl</a></br>
                                    <del>$248.00</del><span class="new_price"> $223.20</span></div>
                                <div class="buy"><a href="http://rosesonly.com.sg/occasion/mother-s-day/24-pink-roses-wholesome-love-gift-box-with-dom-37-5cl.html"><div class="right odd"> BUY</div></a></div></div></td>
                    </tr>
                </table>
            </div>
            <img style="float: right;margin-right: 35px;" src="http://rosesonly.com.sg/skin/frontend/default/f002/special/mother_2014/top-tip.png" />
            <div class="soothing_love">
                <table>
                    <?php $_product = Mage::getModel('catalog/product')->load($product_ids[10]); ?>
                    <tr>
                        <td><a href="http://rosesonly.com.sg/occasion/mother-s-day/12-pink-roses-soothing-love-gift-box-with-osim-eye-massager.html"><img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(175,175);?>" /></a></td>
                    </tr>
                    <tr><td><div class="prd_info"><div class="left"><a href="http://rosesonly.com.sg/occasion/mother-s-day/12-pink-roses-soothing-love-gift-box-with-osim-eye-massager.html">12 Pink Roses
                                    Soothing Love Gift Box
                                    with OSIM Eye Massager</a></br>
                                    <del>$177.00</del><span class="new_price"> $159.30</span></div>
                                <div class="buy"><a href="http://rosesonly.com.sg/occasion/mother-s-day/12-pink-roses-soothing-love-gift-box-with-osim-eye-massager.html"><div class="right odd"> BUY</div></a></div></div></td>
                    </tr>
                    <?php $_product = Mage::getModel('catalog/product')->load($product_ids[11]); ?>
                    <tr>
                        <td><a href="http://rosesonly.com.sg/occasion/mother-s-day/24-pink-roses-soothing-love-gift-box-with-osim-eye-massager.html"><img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(175,175);?>" /></a></td>
                    </tr>
                    <tr><td><div class="prd_info"><div class="left"><a href="http://rosesonly.com.sg/occasion/mother-s-day/24-pink-roses-soothing-love-gift-box-with-osim-eye-massager.html">24 Pink Roses
                                    Soothing Love Gift Box
                                    with OSIM Eye Massager</a></br>
                                    <del>$256.00</del><span class="new_price"> $230.40</span></div>
                                <div class="buy"><a href="http://rosesonly.com.sg/occasion/mother-s-day/24-pink-roses-soothing-love-gift-box-with-osim-eye-massager.html"><div class="right odd"> BUY</div></a></div></div></td>
                    </tr>
                </table>
            </div>
            <div class="gracious_love">
                <table>
                    <?php $_product = Mage::getModel('catalog/product')->load($product_ids[12]); ?>
                    <tr>
                        <td><a href="http://rosesonly.com.sg/occasion/mother-s-day/8-pink-roses-4-lilies-gracious-love-gift-box.html"><img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(175,175);?>" /></a></td>
                    </tr>
                    <tr><td><div class="prd_info"><div class="left"><a href="http://rosesonly.com.sg/occasion/mother-s-day/8-pink-roses-4-lilies-gracious-love-gift-box.html">8 Pink Roses & 4 Lilies
                                    Gracious Love Gift Box</a></br>
                                    <del>$139.00</del><span class="new_price"> $125.10</span></div>
                                <div class="buy"><a href="http://rosesonly.com.sg/occasion/mother-s-day/8-pink-roses-4-lilies-gracious-love-gift-box.html"><div class="right odd"> BUY</div></a></div></div></td>
                    </tr>
                    <?php $_product = Mage::getModel('catalog/product')->load($product_ids[13]); ?>
                    <tr>
                        <td><a href="http://rosesonly.com.sg/occasion/mother-s-day/12-pink-roses-6-lilies-gracious-love-gift-box.html"><img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(175,175);?>" /></a></td>
                    </tr>
                    <tr><td><div class="prd_info"><div class="left"><a href="http://rosesonly.com.sg/occasion/mother-s-day/12-pink-roses-6-lilies-gracious-love-gift-box.html">12 pink roses & 6 Lilies
                                    Gracious Love Gift Box</a></br>
                                    <del>$179.00</del><span class="new_price"> $161.10</span></div>
                                <div class="buy"><a href="http://rosesonly.com.sg/occasion/mother-s-day/12-pink-roses-6-lilies-gracious-love-gift-box.html"><div class="right odd"> BUY</div></a></div></div></td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="footer">
            <div class="footer-info">
                <div>
			            <span>
			                <a href="http://rosesonly.com.sg/security/">Security</a>
			                |<a href="http://rosesonly.com.sg/privacy/">Privacy</a>
			                |<a href="http://rosesonly.com.sg/delivery/">Delivery</a>
			                |<a href="http://rosesonly.com.sg/refunds/">Refunds</a>
			                |<a href="http://rosesonly.com.sg/faq/">FAQ</a>
			                |<a href="http://rosesonly.com.sg/contacts/">Contact us</a>
			            </span>
                </div>
                <div class="clearBoth"></div>
                <div class="label-payment"><span>Available Payment Methods</span></div>
                <div class="footer-payment"></div>
            </div>
            <div class="footer-container">
                <p class="legality y">
                    &copy; 2014 Roses Only Singapore - Order the finest roses online from the leading Australian online florist. Get the best long stemmed boxed roses delivered by Roses Only Singapore, a collaboration with FarEastFlora.com and let us help you to ensure your girlfriend, wife or just that special person knows you love and appreciate them.</p>

            </div>
        </div>
    </div>
</div>
<div style="background: url('http://rosesonly.com.sg/skin/frontend/default/f002/special/mother_2014/bgr-container.png'); height:30px; width:902px; margin:auto;"></div>
</body>
</html>