<html>
    <head>
        <title>Roses Only Singapore</title>
        <link rel="icon" href="/media/favicon/default/Fab_1.jpg" type="image/x-icon" />
        <link rel="shortcut icon" href="/media/favicon/default/Fab_1.jpg" type="image/x-icon" />
        <style media="screen" type="text/css">
            body{padding:0;margin:0;}
            maing{margin:auto;}
        </style>
    </head>
    <body>
        <div class="main">
            <?php echo $this->getChildHtml('content') ?>
        </div>
    </body>
</html>