<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Roses Only Singapore</title>
</head>
<body>
<div>
    <table width="1092px" style="border-spacing:0;padding: 0;border: 0;font-family: Calibri;color:#000;margin:auto;">
        <tr style="border: 0;">
            <td width="220px"></td>
            <td style="text-align:center;"> 
				<div style="width:652px;">
                <a href="http://rosesonly.com.sg/special/mother/edm" style="text-decoration:none;color:#000000;">
				View eNewsletter online
				</a>
				<img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/view_eNewsletter_online.png" />
				</div>
                <table width="652px" style="border-spacing:0px;">
                    <tr>
                        <td>
                            <div class="head">
                                <table width="100%;" style= "border: 0;border-spacing: 0;">
                                    <tr>
                                        <td width="155px">
                                            <div class="head-logo" style="width:155px;float:left;padding-top: 12px;padding-left: 10px;">
                                                <a href="http://rosesonly.com.sg/">
                                                    <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/edm_thankyou_logo.png" />
                                                </a>
                                            </div>
                                        </td>
                                        <td text-align="right">
                                            <div class="head-bar">
                                               
                                                <div class="menu" style="float:right;padding: 65px 5px 0;">
                                                    <a href="http://rosesonly.com.sg" style="text-decoration: none; font-size:13px;color:#000000;padding: 0 5px;display: inline-block;">Home</a>
                                                    <a href="http://rosesonly.com.sg/birthday.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;display: inline-block;">Birthday</a>
                                                    <a href="http://rosesonly.com.sg/occation.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;display: inline-block;">Occasion</a>
                                                    <a href="http://rosesonly.com.sg/recipent.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;display: inline-block;">Recipient</a>
                                                    <a href="http://rosesonly.com.sg/style.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;display: inline-block;">Style</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>                                    
                                </table>                               

                        </td>
                    </tr>
                </table>          

                <div style="width:652px;padding-left:7px;">
                    <a href="http://rosesonly.com.sg/whats-new/surprise-the-piscean.html">
                        <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/mday_banner.png" />
                    </a>
                </div>
				<div style="font:calibri;font-size:20px;color:#675f63;padding-top: 5px;padding-bottom: 5px;">
					<p>When only the best will do for your Mum, you can rest assured Roses Only<br> is the florist you can trust to deliver your love this Mother's Day.</p>
				</div>
                <table width="652" style="margin: auto;" background="http://rosesonly.com.sg/skin/frontend/default/f002/images/pink_border.png">
                    <tr>                  
                        <td>
                            <div style="width:612px;padding-top: 10px;padding-left: 20px;">
                                <a href="http://rosesonly.com.sg/mday13">
                                    <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/geisha.png" />
                                </a>
                            </div>
                        </td>
                    </tr>
                    <tr>                  
                        <td>
                            <div style="width:612px;padding-left: 26px;">
                                <a href="http://rosesonly.com.sg/mday13">
                                    <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/nv.png" />
                                </a>
                            </div>
                        </td>
                    </tr>
					 <tr>                  
                        <td>
                            <div style="width:617px;padding-left: 9px;padding-bottom:30px;">
                                <a href="http://rosesonly.com.sg/mday13">
                                    <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/liles.png" />
                                </a>
                            </div>
                        </td>
                    </tr>
                </table>            
                <div style="height:10px;"></div>
				<div style="width:652px;padding-left:7px;">
					<a href="http://rosesonly.com.sg/mday13">
						<img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/bot_banner1.png" />
					</a>
				</div>
				<div style="height:10px;"></div>
				<table width="652px" style="border-spacing:0px;">
					<td>
						<tr>
						<div style="width:321px;float:left;padding-left:7px;">
							<a href="http://rosesonly.com.sg/mday13">
								<img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/bot_banner2.png" />
							</a>
						</div>
						
						
						<div style="width:321px;float:right;">
							<a href="http://woobox.com/c9eois">
								<img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/bot_banner3.png" />
							</a>
						</div>
						
						</tr>
					</td>
				</table>
				<div style="height:10px;"></div>
				
               
                <div class="edm-contact" style="width:100%;height:75px;text-align: center;padding-left: 3px;">
                    <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/edm_thankyou_contact.png" />
                </div>
                <div class="edm-footer" style=" margin-bottom: 30px;padding: 15px 50px 0px;text-align: center;font-size:15px;color: #231f20;">
                    <div class="footer-bar" style=" border-bottom: 1px solid #231f20; padding-bottom: 8px;">
                        <a href="http://rosesonly.com.sg/customer/account/login/" style="color: #231f20; text-decoration: none;">Log in</a>
                        <span>|</span>
                        <a href="mailto:news@erosesonlysg.com?subject=Subscribe" style="color: #231f20; text-decoration: none;">Subscribe</a>
                        <span>|</span>
                        <a href="mailto:news@erosesonlysg.com?subject=Unsubscribe" style="color: #231f20; text-decoration: none;">Unsubscribe</a>
                        <span>|</span>
                        <a href="http://rosesonly.com.sg/privacy/" style="color: #231f20; text-decoration: none;">Terms & Conditions</a>
                    </div>
                    <div class="footer-bar2" style=" padding:5px 0px; font-size: 15px;">
                        <a href="http://rosesonly.com.sg/privacy/" style="color: #231f20;">Terms & Conditions apply</a>
                    </div>
                    <div class="footer-msg">Roses Only Asia Pte Ltd</div>
                    <div class="footer-msg">You received this newsletter because you have registered with us and agreed to be contacted about our upcoming events and exclusive promotions.</div>
                </div>
            </td>
            <td width="205px" style="border: 0;"></td>
        </tr>
        <tr><td><div style="height:20px;"></div></td></tr>
    </table>
</div>
</body>
</html>