<table width="1000px" background="http://rosesonly.com.sg/skin/frontend/default/f002/images/vday/bg.png" style="font-family: Calibri;color:#000;margin:auto;">
    <tr>
        <td width="150px"></td>
        <td>
            <!--div style="padding-top:20px;color:#333; font-weight:bold;font-size:14px;margin:auto; text-align:center">Does this page look broken? View it in your <a href="http://rosesonly.com.sg/signup/thankyou"style="color: #231f20;">web browser ></a></div-->
            <div style="width:696px;margin:auto;padding-top: 50px; padding-bottom: 30px;">
                <div class="header-break" style="width: 698px;height:10px;background-color:#76A192;"></div>
                <table class="main-container col1-layout" bgcolor="#fff" style="border-spacing:0px;background-color:#fff;">
                    <tr>
                        <td>
                            <div class="head">
                                <table width="100%">
                                    <tr>
                                        <td width="155px">
                                            <div class="head-logo" style="width:155px;float:left;padding-top: 15px;padding-left: 10px;">
                                                <a href="http://rosesonly.com.sg/">
                                                    <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/edm_thankyou_logo.png" />
                                                </a>
                                            </div>
                                        </td>
                                        <td text-align="right">
                                            <div class="head-bar">
                                                <div class="social" style="padding: 40px 20px 0;float:right;">
                                                    <!-- AddThis Button BEGIN -->
                                                    <span style="float:left; padding: 5px 10px;">Share</span>
                                                    <a href="http://api.addthis.com/oexchange/0.8/forward/facebook/offer?pco=tbx32nj-1.0&url=http://rosesonly.com.sg&pubid=ra-50b6d2b601c4ca21" target="_blank" ><img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/23x23/facebook.png" border="0" alt="Facebook" /></a>
                                                    <a href="http://api.addthis.com/oexchange/0.8/forward/twitter/offer?pco=tbx32nj-1.0&url=http%://rosesonly.com.sg&pubid=ra-50b6d2b601c4ca21" target="_blank" ><img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/23x23/twitter.png" border="0" alt="Twitter" /></a>
                                                    <!--a href="http://api.addthis.com/oexchange/0.8/forward/pinterest/offer?pco=tbx32nj-1.0&url=http%3A%2F%2Frosesonly.com.sg&pubid=ra-50b6d2b601c4ca21" target="_blank" ><img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/23x23/pinterest.png" border="0" alt="Twitter" /></a-->
                                                    <a href="http://api.addthis.com/oexchange/0.8/forward/email/offer?pco=tbx32nj-1.0&url=http://rosesonly.com.sg&pubid=ra-50b6d2b601c4ca21" target="_blank" ><img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/23x23/email.png" border="0" alt="Twitter" /></a>
                                                    <!-- AddThis Button END -->
                                                </div>
                                                <div style="clear:both;"></div>
                                                <div class="menu" style="float:right;padding: 15px 20px 0;">
                                                    <a href="http://rosesonly.com.sg" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;">Home</a>
                                                    <a href="http://rosesonly.com.sg/birthday.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;">Birthday</a>
                                                    <a href="http://rosesonly.com.sg/occation.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;">Occasion</a>
                                                    <a href="http://rosesonly.com.sg/recipent.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;">Recipent</a>
                                                    <a href="http://rosesonly.com.sg/style.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;">Style</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                                <div class="ribbon" style="width: 272px; height: 36px; display: block;clear: both; left: -30px; top:-15px; position: relative;"> <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/vday/edm/ribbon.png" /></div>
                            </div>
                            <div style="clear:both;"></div>
                            <div style="width:696px;height:468px;">
                                <a href="http://rosesonly.com.sg/occasion/valentine-s-day/12-red-rose-cherished-love-gift-box.html?limit=all"><img src ="http://rosesonly.com.sg/skin/frontend/default/f002/images/vday/edm/p1.png" /></a> 
                            </div>

                            <div style="width: 636px; margin: auto;margin-top:40px; margin-bottom: 7px;">
                                <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/vday/edm/other.png"/>
                            </div>
                            <div class="content" style="text-align: center;">
                                <table style="width: 696px; margin: auto;text-align: center;">
                                    <tr>
                                        <td width="30px"></td>
                                        <td><a href="http://rosesonly.com.sg/occasion/valentine-s-day/12-red-rose-forever-love-gift-box.html?limit=all"><img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/vday/edm/p2.png"/></a></td>
                                        <td><a href="http://rosesonly.com.sg/occasion/valentine-s-day/12-red-roses-sweet-love-gift-box.html?limit=all"><img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/vday/edm/p3.png"/></a></td>
                                        <td width="30px"></td>
                                    </tr>
                                    <tr style="color: #231f20;font-weight: bold;font-size: 14px;">
                                        <td width="30px"></td>
                                        <td>12 Red Roses<br/>with Moet & Champagne<br/>(Half bottle) and Charlie Plush</td>
                                        <td>12 Red Roses<br/>with Lindt Swiss Thins Chocolate (125g)<br/>and Charlie Plush</td>
                                        <td width="30px"></td>
                                    </tr>
                                    <tr style="color: #be1111;font-weight: bold;font-size: 16px;">
                                        <td width="30px"></td>
                                        <td>EDM Special SGD$170.10 (w/gst SGD$182.01)</td>
                                        <td>EDM Special SGD$143.10 (w/gst SGD$153.12)</td>
                                        <td width="30px"></td>
                                    </tr>
                                    <tr style="color: #be1111;font-size: 16px;" >
                                        <td width="30px"></td>
                                        <td>U.P.SGD$232.51</td>
                                        <td>U.P.SGD$200.41</td>
                                        <td width="30px"></td>
                                    </tr>
                                    <tr style="color: #608a7b;font-weight: bold;">
                                        <td width="30px"></td>
                                        <td>(free delivery before 10 Feb)</td>
                                        <td>(free delivery before 10 Feb)</td>
                                        <td width="30px"></td>
                                    </tr>
                                    <tr>
                                        <td width="30px"></td>
                                        <td><a href="http://rosesonly.com.sg/occasion/valentine-s-day/12-red-rose-forever-love-gift-box.html?limit=all"> <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/vday/button_text.png" /></a></td>
                                        <td><a href="http://rosesonly.com.sg/occasion/valentine-s-day/12-red-roses-sweet-love-gift-box.html?limit=all"> <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/vday/button_text.png" /></a></td>
                                        <td width="30px"></td>
                                    </tr>
                                </table>
                                <div style="margin: 17px 0 9px;font-size: 14px;">Prices stated includes delivery charges and 7% GST tax.</div>
                            </div>

                            <div><a href="http://rosesonly.com.sg"><img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/vday/edm/more.png"/></a></div>

                            <div style="clear:both;height:12px;"></div>
                            <div class="edm-contact" style="width:100%;height:75px;text-align: center;"> <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/edm_thankyou_contact.png" /></div>
                            <div class="edm-footer" style=" margin-bottom: 30px;padding: 15px 50px 50px;text-align: center;font-size:15px;color: #231f20;">
                                <div class="footer-bar" style=" border-bottom: 1px solid #231f20; padding-bottom: 8px;">
                                    <a href="http://rosesonly.com.sg/customer/account/login/" style="color: #231f20; text-decoration: none;">Log in</a>
                                    <span>|</span>
                                    <a href="http://rosesonly.com.sg/birthday.html" style="color: #231f20; text-decoration: none;">Subscribe</a>
                                    <span>|</span>
                                    <a href="http://rosesonly.com.sg/occasion.html" style="color: #231f20; text-decoration: none;">Unsubscribe</a>
                                    <span>|</span>
                                    <a href="http://rosesonly.com.sg/privacy/" style="color: #231f20; text-decoration: none;">Terms & Conditions</a>
                                </div>
                                <div class="footer-bar2" style=" padding:5px 0px; font-size: 15px;">
                                    <a href="http://rosesonly.com.sg/privacy/" style="color: #231f20;">Terms & Conditions apply</a>
                                </div>
                                <div class="footer-msg">Roses Only Asia Pte Ltd</div>
                                <div class="footer-msg">You received this newsletter because you have registered with us and agreed to be contacted about our upcoming events and exclusive promotions.</div>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </td>
        <td width="150px"></td>
    </tr>
</table>