<div class="head">
    <div class="head-logo">
        <a href="http://rosesonly.com.sg/">
            <div class="edm-logo"></div>
        </a>
    </div>
    <div class="head-bar">
        <div class="social">          
            <!-- AddThis Button BEGIN -->            
            <span style="float:left; padding: 5px 10px;">Share</span>
            <span class="addthis_toolbox addthis_default_style">
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_pinterest_share"></a>
                <a class="addthis_button_email"></a>
                <a class="addthis_button_print"></a>
            </span>
            
            <script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
            <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-50b6d2b601c4ca21"></script>
            <!-- AddThis Button END -->
        </div>
        <div style="clear:both;"></div>
        <div class="menu">
            <a href="http://rosesonly.com.sg">Home</a>
            <a href="http://rosesonly.com.sg/birthday.html">Birthday</a>
            <a href="http://rosesonly.com.sg/occation.html">Occasion</a>
            <a href="http://rosesonly.com.sg/recipent.html">Recipent</a>
            <a href="http://rosesonly.com.sg/style.html">Style</a>
        </div>
    </div>    
    <div class="ribbon"></div>
</div>
<div style="clear:both;"></div>
<div class="edm-thankyou"></div>
<div class="content">
    <div class="content-left">
        <div class="message">
            <div class="label">
                Dear Customer,
            </div>
            <div class="label">
                You can now receive first-hand our latest updates and exclusive offers in your inbox!
            </div>
            <div class="label">
                To show our appreciation, here's a gift to get your shopping started. Enjoy <span class="discount">10% discount</span> on your 1st purchase sitewide by selecting your roses and keying in <span class="coupon">"RosesOnly"</span> when you check out. Read on for more details on your redemption!
            </div>
            <div class="label">
                Have fun shopping!
            </div>
            <div class="label">
                Warmest Regards,
            </div>
            <div class="edm-name">
            </div>
        </div>
    </div>
    <div class="content-right">
        <div class="discount-image"></div>
    </div>
</div>
<div style="clear:both;"></div>
<div class="edm-foot"></div>
<div class="ads">
    <div class="ads-left"></div>
    <a href="http://rosesonly.com.sg/style/roses-only/long-stemmed-roses-gift-box-295.html">
        <div class="ads-right"></div>
    </a>
</div>
<div style="clear:both;height:10px;"></div>
<div class="edm-contact"></div>
<div class="edm-footer">
    <div class="footer-bar">
        <a href="<?php echo Mage::getUrl('customer/account/login/') ?>">Log in</a>
        <span>|</span>
        <a href="http://rosesonly.com.sg">Subscribe</a>
        <span>|</span>
        <a href="<?php echo Mage::getUrl('unsubscribe') ?>">Unsubscribe</a>
        <span>|</span>
        <a href="http://rosesonly.com.sg/privacy/">Terms & Conditions</a>        
    </div>
    <div class="footer-bar2">
        <a href="http://rosesonly.com.sg/privacy/">Terms & Conditions apply</a>
    </div>
    <div class="footer-msg">Roses Only Asia Pte Ltd</div>
    <div class="footer-msg">You received this newsletter because you have registered with us and agreed to be contacted about our upcoming events and exclusive promotions.</div>
</div>