<a href="http://rosesonly.com.sg/"><div class="signup-logo"></div></a>
<div class="signup-thankyou"></div>

<div class="thankyou-message">
    <div class="label">
        You will be receiving an email from us very soon.
    </div>
    <div class="label">
        To complete the subscription process, please click on the confirmation link in the email.
    </div>
    
    <div class="sign">
        Warmest regards,
        <br/>     
        Team @ Roses Only Singapore
    </div>
</div>
<div class="thankyou-footer"></div>