<?php
/**
 * @author      Hoang Dinh
 */
?>
<?php if( Mage::getStoreConfig('ibanners/settings/enable')==1):?>
<div id="ibanner">
    <div id="ibanner-image">
        <?php if ($this->hasValidGroup()): ?>  
            <?php $group = $this->getGroup(); ?>
            <?php $banners = $this->getBanners() ?>
            <?php if ($this->getGroup()->getBannerCount() == 1): ?>
                <div id="<?php echo $this->getWrapperId() ?>" class="ibanners-single <?php echo $this->getWrapperClass() ?>">
                    <?php foreach ($banners as $banner): ?>
                        <?php if ($banner->hasUrl()): ?>
                            <a href="<?php echo $banner->getUrl() ?>" title="<?php echo $this->escapeHtml($banner->getTitle()) ?>">
                            <?php endif; ?>
            <!--img name="img" id="img" src="<?php echo $banner->getImageUrl() ?>" alt="<?php echo $this->escapeHtml($banner->getAltText()) ?>" /-->
                            <div style="width:100%;height:100%; background: url('<?php echo $banner->getImageUrl() ?>'); background-size: 100% 100%;background-repeat:none;"></div>
                            <?php if ($banner->hasUrl()): ?>
                            </a>
                        <?php endif; ?>
                        <?php if ($banner->getHtml()): ?>
                            <div class="html"><?php echo $banner->getHtml() ?></div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            <?php elseif ($this->getGroup()->getBannerCount() > 1): ?>
                <div id="<?php echo $this->getWrapperId() ?>-wrapper" class="<?php echo $this->getWrapperClass() ?>">
                    <div id="<?php echo $this->getWrapperId() ?>" class="ibanners <?php if ($group->isAnimationEnabled()): ?>animated<?php else: ?>static<?php endif; ?>">
                        <ul>
                            <?php foreach ($banners as $banner): ?>
                                <li id="ibanner-<?php echo $banner->getId() ?>" class="banner">
                                    <?php if ($banner->getImageUrl()): ?>
                                        <?php if ($banner->hasUrl()): ?>
                                            <a href="<?php echo $banner->getUrl() ?>" title="<?php echo $this->escapeHtml($banner->getTitle()) ?>"<?php if ($banner->getUrlTarget()): ?> target="<?php echo $banner->getUrlTarget() ?>"<?php endif; ?>>
                                            <?php endif; ?>
                <!--img name="img"  src="<?php echo $banner->getImageUrl() ?>" alt="<?php echo $this->escapeHtml($banner->getAltText()) ?>" /-->
                                            <div style="width:100%;height:100%; background: url('<?php echo $banner->getImageUrl() ?>'); background-size: 100% 100%;background-repeat:none;"></div>
                                            <?php if ($banner->hasUrl()): ?>
                                            </a>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if ($banner->getHtml()): ?>
                                        <div class="html"><?php echo $banner->getHtml() ?></div>
                                    <?php endif; ?>
                                </li>
                            <?php endforeach; ?>
                            <?php if ($group->isAnimationEnabled() && $this->getGroup()->getCarouselEffect() != 'fade'): ?>
                                <?php
                                /**
                                 * When using the scroll effect, the first slide must be duplicated at the end of the slide list
                                 * This ensures a smooth scrolling action when moving between the last and first slide
                                 */
                                ?>
                                <?php $banner = $banners->getFirstItem() ?>
                                <li id="ibanner-<?php echo $banner->getId() . '-2' ?>" class="banner">
                                    <?php if ($banner->getImageUrl()): ?>
                                        <?php if ($banner->hasUrl()): ?>
                                            <a href="<?php echo $banner->getUrl() ?>" title="<?php echo $this->escapeHtml($banner->getTitle()) ?>"<?php if ($banner->getUrlTarget()): ?> target="<?php echo $banner->getUrlTarget() ?>"<?php endif; ?>>
                                            <?php endif; ?>
                <!--img name="img" src="<?php echo $banner->getImageUrl() ?>" alt="<?php echo $this->escapeHtml($banner->getAltText()) ?>" /-->
                                            <div style="width:100%;height:100%; background: url('<?php echo $banner->getImageUrl() ?>'); background-size: 100% 100%;background-repeat:none;"></div>
                                            <?php if ($banner->hasUrl()): ?>
                                            </a>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if ($banner->getHtml()): ?>
                                        <div class="html"><?php echo $banner->getHtml() ?></div>
                                    <?php endif; ?>
                                </li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>                    
            <?php endif; ?>
        <?php endif; ?>
    </div>        
</div>
<script language="JavaScript" type="text/javascript">
    //window.onbeforeunload = confirmExit;   
    window.onunload = confirmExit;
    window.innerWidth = 672;
    window.innerHeight = 271;
    var w = window.innerWidth;
    var h =  window.innerHeight;
    function confirmExit()
    {                  
        if (getCookie('popup')!='true'){
            var left = (screen.width/2)-(w/2);
            var top = (screen.height/2)-(h/2);
            mywindow = window.open('special/popup','Roses Only Singapore','toolbar=no, location=0, directories=0, status=no, menubar=no, scrollbars=no, resizable=false, copyhistory=no, width='+w+', height='+h+', top='+top+', left='+left);        
            mywindow.focus();
            setCookie('popup','true',1);            
        }        
    }
    
    function setCookie(c_name,value,exdays)
    {
        var exdate=new Date();
        exdate.setDate(exdate.getDate() + exdays);
        var c_value=escape(value) + ((exdays==null) ? "" : "; expires="+exdate.toUTCString());
        document.cookie=c_name + "=" + c_value;
    }

    function getCookie(c_name)
    {
        var i,x,y,ARRcookies=document.cookie.split(";");
        for (i=0;i<ARRcookies.length;i++)
        {
            x=ARRcookies[i].substr(0,ARRcookies[i].indexOf("="));
            y=ARRcookies[i].substr(ARRcookies[i].indexOf("=")+1);
            x=x.replace(/^\s+|\s+$/g,"");
            if (x==c_name)
            {
                return unescape(y);
            }
        }
    }
</script>

<?php endif;?>