<div>
    <table width="1092px" background="http://rosesonly.com.sg/skin/frontend/default/f002/images/aries/bg.png" style="border-spacing:0;padding: 0;border: 0;font-family: Calibri;color:#000;margin:auto;background-repeat: no-repeat;padding-bottom: 40px;">
        <tr style="border: 0;">
            <td width="192px"></td>
            <td style="text-align:center;"> 
                <div style="padding:30px 0 15px;color:#333; font-weight:bold;font-size:14px;margin:auto; text-align:center">
                    Does this page look broken? View it in your <a href="http://rosesonly.com.sg/special/aries/edm" style="color: #231f20;">web browser ></a>
                </div>
                <table width="100%" style="border-spacing:0px;">
                    <tr>
                        <td>
                            <div class="head">
                                <table width="100%;" style= "border: 0;border-spacing: 0;">
                                    <tr>
                                        <td width="155px">
                                            <div class="head-logo" style="width:155px;float:left;padding-top: 12px;padding-left: 10px;">
                                                <a href="http://rosesonly.com.sg/">
                                                    <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/edm_thankyou_logo.png" />
                                                </a>
                                            </div>
                                        </td>
                                        <td text-align="right" width="525px">
                                            <div class="head-bar">
                                                <div class="social" style="padding: 10px 20px 0;float:right;">
                                                    <!-- AddThis Button BEGIN -->
                                                    <span style="float:left; padding: 5px 10px;">Share</span>
                                                    <a href="http://api.addthis.com/oexchange/0.8/forward/facebook/offer?pco=tbx32nj-1.0&url=http://rosesonly.com.sg&pubid=ra-50b6d2b601c4ca21" target="_blank" ><img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/23x23/facebook.png" border="0" alt="Facebook" /></a>
                                                    <a href="http://api.addthis.com/oexchange/0.8/forward/twitter/offer?pco=tbx32nj-1.0&url=http%://rosesonly.com.sg&pubid=ra-50b6d2b601c4ca21" target="_blank" ><img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/23x23/twitter.png" border="0" alt="Twitter" /></a>
                                                    <!--a href="http://api.addthis.com/oexchange/0.8/forward/pinterest/offer?pco=tbx32nj-1.0&url=http%3A%2F%2Frosesonly.com.sg&pubid=ra-50b6d2b601c4ca21" target="_blank" ><img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/23x23/pinterest.png" border="0" alt="Twitter" /></a-->
                                                    <a href="http://api.addthis.com/oexchange/0.8/forward/email/offer?pco=tbx32nj-1.0&url=http://rosesonly.com.sg&pubid=ra-50b6d2b601c4ca21" target="_blank" ><img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/23x23/email.png" border="0" alt="Twitter" /></a>
                                                    <!-- AddThis Button END -->
                                                </div>
                                                <div style="clear:both;"></div>
                                                <div style="float:right;"><a href="http://rosesonly.com.sg/special/email?template=aries" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 20px;">Recommend to Friend</a></div>
                                                <div style="clear:both;"></div>
                                                <div class="menu" style="float:right;padding: 5px 20px 0;">
                                                    <a href="http://rosesonly.com.sg" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;">Home</a>
                                                    <a href="http://rosesonly.com.sg/birthday.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;">Birthday</a>
                                                    <a href="http://rosesonly.com.sg/occation.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;">Occasion</a>
                                                    <a href="http://rosesonly.com.sg/recipent.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;">Recipient</a>
                                                    <a href="http://rosesonly.com.sg/style.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;">Style</a>
                                                    <a href="http://rosesonly.com.sg/whats-new/pure-bliss-for-the-aries.html" style="text-decoration: none; font-size:13px;color:#847D7F;padding: 0 5px;">What's new </a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>                                    
                                </table>                               

                                <div style="clear:both;"></div>
                        </td>
                    </tr>
                </table>          

                <div style="width:100%;margin:auto;margin: 33px auto 10px;">
                    <a href="http://rosesonly.com.sg/whats-new/pure-bliss-for-the-aries.html">
                        <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/aries/top.png" />
                    </a>
                </div>
                      
                <div style="width:100%;margin:auto;margin: 3px auto 10px;">
                    <a href="http://rosesonly.com.sg/whats-new/pure-bliss-for-the-aries/my-number-one-sweetness-roses.html">
                        <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/aries/product.png" />
                    </a>
                </div>
                
                <div style="height:225px;"></div>               

                <div style="text-align:center;padding:10px; font-size:14px;">
                    <span>Prices stated does not include delivery charges of $8.56 per location</span>
                </div>
                <div class="edm-contact" style="width:100%;height:75px;text-align: center;">
                    <img src="http://rosesonly.com.sg/skin/frontend/default/f002/images/aries/contact.png" />
                </div>
                <div class="edm-footer" style=" margin-bottom: 30px;padding: 15px 50px 0px;text-align: center;font-size:15px;color: #231f20;">
                    <div class="footer-bar" style=" border-bottom: 1px solid #231f20; padding-bottom: 8px;">
                        <a href="http://rosesonly.com.sg/customer/account/login/" style="color: #231f20; text-decoration: none;">Log in</a>
                        <span>|</span>
                        <a href="mailto:news@erosesonlysg.com?subject=Subscribe" style="color: #231f20; text-decoration: none;">Subscribe</a>
                        <span>|</span>
                        <a href="mailto:news@erosesonlysg.com?subject=Unsubscribe" style="color: #231f20; text-decoration: none;">Unsubscribe</a>
                        <span>|</span>
                        <a href="http://rosesonly.com.sg/privacy/" style="color: #231f20; text-decoration: none;">Terms & Conditions</a>
                    </div>
                    <div class="footer-bar2" style=" padding:5px 0px; font-size: 15px;">
                        <a href="http://rosesonly.com.sg/privacy/" style="color: #231f20;">Terms & Conditions apply</a>
                    </div>
                    <div class="footer-msg">Roses Only Asia Pte Ltd</div>
                    <div class="footer-msg">You received this newsletter because you have registered with us and agreed to be contacted about our upcoming events and exclusive promotions.</div>
                </div>
            </td>
            <td width="204px" style="border: 0;"></td>
        </tr>
        <tr><td><div style="height:20px;"></div></td></tr>
    </table>
</div>