<?php 
/**
 * Yumba Soft
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Yumba
 * @package    Yumba_OrderCancel
 * @copyright  Copyright (c) 2011 Yumba Soft (yumba.soft@gmail.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-head">
    <h3><?php echo $this->__('My Orders') ?></h3>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if($_orders->getSize()): ?>
<table cellspacing="0" class="data-table" id="my-orders-table">
    <thead>
        <tr>
            <th><?php echo $this->__('Order #') ?></th>
            <th><?php echo $this->__('Date') ?></th>
            <!-- <th><?php echo $this->__('Ship to') ?></th> -->
            <th><?php echo $this->__('Order Total') ?></th>
            <th><?php echo $this->__('Order Status') ?></th>
            <th class="last">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_orders as $_order): ?>
            <tr>
                <td><?php echo $_order->getRealOrderId() ?></td>
                <td><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></td>
                <!-- <td><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td> -->
                <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                <td><em><?php echo $_order->getStatusLabel() ?></em></td>
                <td class="a-center"><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View Order') ?></a>
                    <?php /*<span class="separator">|</span><a href="<?php echo $this->getTrackUrl($_order) ?>"><?php echo $this->__('Track Order') ?></a>&nbsp;*/ ?>
                    <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                        <span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" style="font-weight: bold; color: #403A3A;"><?php echo $this->__('Reorder') ?></a>
                    <?php endif ?>
                    <?php /* CHANGES STARTS */ ?>
                    <?php if (true || $_order->canCancel()) { ?>
                        <span class="separator">|</span> 
                        <a href="<?php echo $this->getUrl('sales/order/cancel', array('order_id' => $_order->getId())); ?>" class="order-cancel">
                            <?php echo $this->__('Cancel') ?>
                        </a>
                    <?php } else { ?>
                    	<!-- Order cancel is not available -->
                	<?php } ?>
                	<?php /* CHANGES ENDS */ ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table')</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>



