<?php 
/**
 * Yumba Soft
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Yumba
 * @package    Yumba_OrderCancel
 * @copyright  Copyright (c) 2011 Yumba Soft (yumba.soft@gmail.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<!--<div class="account-box ad-orders">-->
<?php $_orders = $this->getOrders(); ?>
    <!--<div class="box-title">
        <h4><?php /*echo $this->__('PAST ORDERS') */?></h4>
    </div>-->
<?php if( sizeof($_orders->getItems()) > 0 ): ?>
    <div class="box-content">
        <table cellspacing="0" class="data-table" id="my-orders-table">
            <thead>
                <tr style="background-color: #e5e5e5;">
                    <th class="a-center"><?php echo $this->__('Order Number') ?></th>
                    <th class="a-center"><?php echo $this->__('Order Date') ?></th>
                    <!-- <th><?php echo $this->__('Ship to') ?></th> -->
                    <th class="a-center"><?php echo $this->__('Status') ?></th>
                    <th class="a-center"><?php echo $this->__('Total') ?></th>
                    <th class="last"></th>
                </tr>
            </thead>
            <tbody>
            <?php $_odd = ''; ?>
                <?php foreach ($_orders as $_order): ?>
                    <tr class="<?php echo ($_odd = ($_odd ? 'odd' : '')) ?>">
                        <td class="a-center"><?php echo $_order->getRealOrderId() ?>&nbsp;</td>
                        <td class="a-center"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?> </td>
                        <!-- <td><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '' ?>&nbsp;</td> -->
                        <td class="a-center"><em><?php echo $_order->getStatusLabel() ?></em>&nbsp;</td>
                        <td class="a-center"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?>&nbsp;</td>
                        <td class="last a-center"><a href="<?php echo $this->getViewUrl($_order) ?>" style="text-decoration: underline"><?php echo $this->__('View') ?></a>

                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif; ?>
    <br /><br />
    <div><?php if( sizeof($_orders->getItems()) > 0 ): ?><a href="<?php echo $this->getUrl('sales/order/history') ?>" class="past-orders"><span><span><?php echo $this->__('View All') ?></span></span></a><?php endif; ?></div>
<!--</div>-->