<?php
$_helper = $this->helper('catalog/output');
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <div class=" most_viewed">
        <!--div class="mv_title"><?php echo $this->__('These Products Are Popular Right Now!') ?></div-->
        <?php $_columnCount = 4; //count($_products->getItems()); echo $_collectionSize; ?>
            <?php $i = 0;
            foreach ($_products->getItems() as $_product): ?>
            <?php if ($i++ % $_columnCount == 0): ?>
                    <ul class="products-grid quickview-products">
            <?php endif ?>
                <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                     <div class="product-shop">
                         <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(155); ?>" width="155" height="155" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        </a> 
                         <h2 class="product-name">
						 <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?><?php echo $_product->getName()?></a>
						 </h2>
                         <div class="desc std">
                                <?php
                                //echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');
                                $desc = $_product->getShortDescription();
                                if (strlen($desc) > 100) {
                                    $desc = substr($desc, 0, 100) . '...';
                                }
                                echo $desc;
                                ?> 
                          </div>
                          <?php if ($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                          <?php endif; ?>                           
                          <?php if ($_product->getResource()->getAttribute('is_best_seller')->getFrontend()->getValue($_product) == "Yes"): ?>
                              <div class="best-seller">Best Seller</div>
                          <?php endif; ?>
                    </div>
                </li>
                <?php if ($i % $_columnCount == 0 || $i == $_products->getSize()): ?>
                    </ul>
                <?php endif ?>
        <?php endforeach ?>
    </div>
<?php endif; ?>